---
- name: config-sysctl
  tags: preinstall
  block:
  - name: configure sysctl variables for high load
    sysctl: name={{ item.name }} value={{ item.value }} ignoreerrors="true"
    with_items:
    - { name: net.ipv6.conf.all.disable_ipv6, value: 1 }
    - { name: net.ipv4.ip_forward, value: 1 }
    - { name: net.ipv4.conf.default.rp_filter, value: 1 }
    - { name: net.ipv4.conf.all.rp_filter, value: 1 }
    - { name: net.ipv4.icmp_echo_ignore_broadcasts, value: 1 }
    - { name: net.ipv4.tcp_fin_timeout, value: 30 }
    - { name: net.ipv4.tcp_keepalive_time, value: 1800 }
    - { name: net.ipv4.tcp_keepalive_intvl, value: 15 }
    - { name: net.ipv4.tcp_keepalive_probes, value: 5 }
    - { name: net.ipv4.tcp_synack_retries, value: 1 }
    - { name: net.ipv4.tcp_orphan_retries, value: 0 }
    - { name: net.ipv4.tcp_syncookies, value: 0 }
    - { name: net.ipv4.tcp_timestamps, value: 1 }
    - { name: net.ipv4.tcp_sack, value: 1 }
    - { name: net.ipv4.tcp_no_metrics_save, value: 1 }
    - { name: net.ipv4.tcp_tw_reuse, value: 1 }
    - { name: net.ipv4.tcp_window_scaling, value: 1 }
    - { name: net.ipv4.tcp_rfc1337, value: 1 }
    - { name: vm.max_map_count, value: 524288 }
    - { name: vm.swappiness, value: 10 }
    tags:
    - sysctl
